name: Build and publish Windows exe

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PyInstaller
        run: |
          pip install pyinstaller
      - name: Build exe
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico main.py
      - name: Upload exe
        uses: actions/upload-artifact@v2
        with:
          name: exe  # 确保这个名字与下载步骤中的一致
          path: dist/WechatMsg.exe
      - name: Debug
        run: |
          ls -R

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: exe  # 与上传步骤中的名字一致
      - name: Debug
        run: |
          ls -R
      - name: Upload exe to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/WechatMsg.exe
          tag_name: latest
          release_name: Latest Release
